# Already present from inclusivedesign/nodejs container
# - src: https://github.com/idi-ops/ansible-facts
# - src: https://github.com/idi-ops/ansible-nodejs
- src: https://github.com/waharnum/ansible-gpii-flow-manager
  name: flow-manager
